export type OnboardingStackParamList = {
  LocationPermission: undefined;
  Experience: undefined;
  Biometrics: undefined;
  StrengthGoal: undefined;
  Motivation1: undefined;
  Equipment: undefined;
  Focus: undefined;
  RunningInterstitial: undefined;
  RunningGoal: undefined;
  Schedule: undefined;
  Split: undefined;
  Summary: undefined;
  Loading: undefined;
  PlanPreview: undefined;
  Features: undefined;
  Referral: undefined;
  Paywall: undefined;
  Auth: undefined;
};
